version: '2'

services:
  showdoc:
    restart: always
    container_name: showdoc
    image: nills/showdoc:1.4.3
    volumes:
      - ./data/Application:/var/www/html/Application
      - ./data/uploads:/var/www/html/Public/Uploads
      - ./data/Sqlite:/var/www/html/Sqlite
    ports:
      - "11380:80"
